
CREATE database [PROYECTOPROGRA4]
GO
/*drop data base [PROYECTOPROGRA4]
go*/

USE PROYECTOPROGRA4
GO
CREATE SCHEMA [ADMINISTRATIVO]
GO
CREATE SCHEMA [COMERCIAL]
GO
CREATE TABLE [ADMINISTRATIVO].[TIPO_IDENTIFICACION]
(
[ID_TIPO_IDENTIFICACION]  int NOT NULL PRIMARY KEY,
[NOMBRE]varchar (20) NOT NULL
)
GO
CREATE TABLE [ADMINISTRATIVO].[PERSONA]
(
[ID_PERSONA]  int NOT NULL PRIMARY KEY,
[NO_CEDULA] int  NOT NULL,
[NOMBRE] varchar(25) NOT NULL,
[APELLIDO1] varchar(25) NOT NULL,
[APELLIDO2] varchar(25) NOT NULL,
[TIPO_IDENTIFICACION] int FOREIGN KEY REFERENCES [ADMINISTRATIVO].[TIPO_IDENTIFICACION]([ID_TIPO_IDENTIFICACION]),
[GENERO] int FOREIGN KEY REFERENCES [ADMINISTRATIVO].[GENERO]([ID_GENERO]),
[CORREO_ELECTRONICO] varchar(40) NOT NULL,
[TELEFONO] int  NOT NULL,
[FECHA_NACIMIENTO_CONSTITUCION] datetime NOT NULL,
[ESTADO_CIVIL] int FOREIGN KEY REFERENCES [ADMINISTRATIVO].[ESTADO_CIVIL]([ID_ESTADO_CIVIL]),
[APODERADO] varchar (50) NOT NULL,
[PROVINCIA] int FOREIGN KEY REFERENCES [ADMINISTRATIVO].[PROVINCIA]([ID_PROVINCIA]),
[CANTON] int FOREIGN KEY REFERENCES [ADMINISTRATIVO].[CANTON]([ID_CANTON]),
[DISTRITO] int FOREIGN KEY REFERENCES [ADMINISTRATIVO].[DISTRITO]([ID_DISTRITO])
)
GO
CREATE TABLE [ADMINISTRATIVO].[PROVINCIA]
(
[ID_PROVINCIA]  int NOT NULL PRIMARY KEY,
[NOMBRE] varchar(25) 
)
GO
INSERT INTO [ADMINISTRATIVO].[PROVINCIA] ([ID_PROVINCIA],[NOMBRE]) VALUES
(1, 'San José'),
(2, 'Alajuela'),
(3, 'Cartago'),
(4, 'Heredia'),
(5, 'Guanacaste'),
(6, 'Puntarenas'),
(7, 'Limón');  

/*SELECT * FROM [ADMINISTRATIVO].[CANTON]*/

/*delete from [ADMINISTRATIVO].[PROVINCIA] where [ID_PROVINCIA] =1;*/
GO

CREATE TABLE [ADMINISTRATIVO].[CANTON]
(
[ID_CANTON]  int NOT NULL PRIMARY KEY,
[NOMBRE] varchar(25),
[PROVINCIA] int FOREIGN KEY REFERENCES [ADMINISTRATIVO].[PROVINCIA]([ID_PROVINCIA])
)
GO
INSERT INTO [ADMINISTRATIVO].[CANTON] ([ID_CANTON],[NOMBRE],[PROVINCIA]) VALUES
--SAN JOSE
(1, 'San José',1),
(2, 'Escazú',1),
(3, 'Desamparados',1),
(4, 'Puriscal',1),
(5, 'Tarrazú',1),
(6, 'Aserrí',1),
(7, 'Mora',1)
(8, 'Goicoechea',1),
(9, 'Santa Ana',1),
(10, 'Alajuelita',1),
(11, 'Vasquez de Coronado',1),
(12, 'Acosta',1),
(13, 'Tibas',1),
(14, 'Moravia',1),
(15, 'Montes de Oca',1),
(16, 'Turrubares',1),
(17, 'Dota',1),
(18, 'Curridabat',1),
(19, 'Perez Zeledon',1),
(20, 'Leon Cortez',1);  
--ALAJUELA
(21, 'Alajuela',2)
(22, 'San Ramón',2)
(23, 'Grecia',2)
(24, 'San Mateo',2)
(25, 'Atenas',2)
(26, 'Naranjo',2)
(27, 'Palmares',2)
(28, 'Poás',2)
(29, 'Orotina',2)
(30, 'San Carlos',2)
(31, 'Zarceri',2)
(32, 'Valverde Vega',2)
(33, 'Upala',2)
(34, 'Los Chiles',2)
(35, 'Guatuso',2)
(36, 'Río Cuarto',)
--CARTAGO
(37, 'Cartago',3)
(38, 'Paraíso',3)
(39, 'La Unión',3)
(40, 'Jiménez',3)
(41, 'Turrialba',3)
(42, 'Alvarado',3)
(43, 'Oreamuno',3)
(44, 'El Guarco',3)
--HEREDIA
(45, 'Heredia',4)
(46, 'Barva',4)
(47, 'Santo Domingo',4)
(48, 'Santa Bárbara',4)
(49, 'San Rafael',4)
(50, 'San Isidro',4)
(51, 'Belén',4)
(52, 'Flores',4)
(53, 'San Pablo',4)
(54, 'Sarapiquí',4)
--GUANACASTE
(55, 'Liberia',5)
(56, 'Nicoya',5)
(57, 'Santa Cruz',5)
(58, 'Bagaces',5)
(59, 'Carrillo',5)
(60, 'Cañas',5)
(61, 'Abangares',5)
(62, 'Tilarán',5)
(63, 'Nandayure',5)
(64, 'La Cruz',5)
(65, 'Hojancha',5)
--PUNTARENAS
(66, 'Puntarenas',6)
(67, 'Esparza',6)
(68, 'Buenos Aires',6)
(69, 'Montes de Oro',6)
(70, 'Osa',6)
(71, 'Quepos',6)
(72, 'Golfito',6)
(73, 'Coto Brus',6)
(74, 'Parrita',6)
(75, 'Corredores',6)
(76, 'Garabito',6)
--LIMON
(77, 'Limón',7)
(78, 'Pococí',7)
(79, 'Siquirres',7)
(80, 'Talamanca',7)
(81, 'Matina',7)
(82, 'Guácimo',7)

GO




CREATE TABLE [ADMINISTRATIVO].[DISTRITO]
(
[ID_DISTRITO]  int NOT NULL PRIMARY KEY,
[NOMBRE] varchar(25),
[CANTON] int FOREIGN KEY REFERENCES [ADMINISTRATIVO].[CANTON]([ID_CANTON])
)
GO
INSERT INTO [ADMINISTRATIVO].[DISTRITO][ID_DISTRITO]  [NOMBRE],[CANTON] ) VALUES



CREATE TABLE [ADMINISTRATIVO].[GENERO]
(
[ID_GENERO]  int NOT NULL PRIMARY KEY,
[TIPO] varchar(25)
)
GO
CREATE TABLE [ADMINISTRATIVO].[ESTADO_CIVIL]
(
[ID_ESTADO_CIVIL]  int NOT NULL PRIMARY KEY,
[ESTADO] varchar(25)
)
GO
CREATE TABLE [ADMINISTRATIVO].[USUARIO]
(
[ID_USUARIO]  int NOT NULL PRIMARY KEY,
[NOMBRE] varchar(25),
[CONTRASEÑA] varchar(25),
[ROL] int,
[PERSONA] int FOREIGN KEY REFERENCES [ADMINISTRATIVO].[PERSONA]([ID_PERSONA])
)
GO
CREATE TABLE [COMERCIAL].[POLIZA]
(
[ID_POLIZA]  int NOT NULL PRIMARY KEY,
[USUARIO] int FOREIGN KEY REFERENCES [ADMINISTRATIVO].[USUARIO]([ID_USUARIO]),
[NOMBRE] varchar(25),
[DESCRIPCION] varchar(25),
[PERSONA] int FOREIGN KEY REFERENCES [ADMINISTRATIVO].[PERSONA]([ID_PERSONA]),
[PLAN] int FOREIGN KEY REFERENCES [COMERCIAL].[PLANES]([ID_PLAN])
)
GO
CREATE TABLE [COMERCIAL].[PLANES]
(
[ID_PLAN]  int NOT NULL PRIMARY KEY,
[NOMBRE] varchar(25),
[COSTO] money,
[COBERTURA] int FOREIGN KEY REFERENCES [COMERCIAL].[COBERTURA]([ID_COBERTURA])
)
GO
CREATE TABLE [COMERCIAL].[COBERTURA]
(
[ID_COBERTURA]  int NOT NULL PRIMARY KEY,
[NOMBRE] varchar(25),
[MONTO] money,
[CANT_EVENTOS] int,
[CANT_BENEFICIARIOS] int
)
GO
CREATE TABLE [COMERCIAL].[TARJETA_CREDITO&DEintO]
(
[ID_TARJETA_CREDITO&DEintO]  int NOT NULL PRIMARY KEY,
[NUMERO] int,
[BANCO_EMISOR] varchar(50),
[FECHA_VENCIMIENTO] date
)
GO
CREATE TABLE [COMERCIAL].[VENTA]
(
[ID_VENTA]  int NOT NULL PRIMARY KEY,
[POLIZA] int FOREIGN KEY REFERENCES [COMERCIAL].[POLIZA]([ID_POLIZA]),
[TARJETA_CREDITO&DEintO] int FOREIGN KEY REFERENCES [COMERCIAL].[TARJETA_CREDITO&DEintO]([ID_TARJETA_CREDITO&DEintO])
)
